---
- name: AS3 delete
  hosts: big-ip
  connection: local
  gather_facts: false

  tasks:
    - name: remove as3 deployment
      uri:
        url: "https://{{ ansible_host }}/mgmt/shared/appsvcs/declare/"
        method: DELETE
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: yes
        user: "{{ bigip_user }}"
        password: "{{ bigip_password }}"
        validate_certs: no
      delegate_to: localhost


