---
- hosts: big-ip-01
  connection: local
  tasks:
    - name: Import APM Policy
      bigip_apm_policy_import:
        name: simple-policy
        source: /home/romain/ansible-playbooks/artifact/profile_Common_simple_policy.conf.tar.gz
        type: access_policy
        provider: 
          server: "{{ ansible_host }}"
          user: "{{ bigip_user }}"
          password: "{{ bigip_password }}"
          validate_certs: no
      delegate_to: localhost
