---
- hosts: app-servers
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'install Python2'
      raw: sudo apt-get -y install python
  tasks:
    - name: copy ip_address.txt
      copy:
        src: ./artifact/ip_address.txt
        dest: /home/romain/ip_address.txt
        owner: romain

    - name: copy load_script.sh
      copy:
        src: ./artifact/load_script.sh
        dest: /home/romain/load_script.sh
        owner: romain

    - name: execute the script
      command: sh /home/romain/load_script.sh
